describe("aiService", function () {
    it("Player 0 finds an immediate first Move", function () {
        var move = aiService.createComputerMove(0, { "tile0": { "leftNumber": 2, "rightNumber": 6 }, "tile1": { "leftNumber": 0, "rightNumber": 5 }, "tile2": { "leftNumber": 4, "rightNumber": 5 }, "tile3": { "leftNumber": 1, "rightNumber": 2 }, "tile4": { "leftNumber": 6, "rightNumber": 6 }, "tile5": { "leftNumber": 1, "rightNumber": 1 }, "tile6": { "leftNumber": 3, "rightNumber": 3 }, "tile7": null, "tile8": null, "tile9": null, "tile10": null, "tile11": null, "tile12": null, "tile13": null, "tile14": null, "tile15": null, "tile16": null, "tile17": null, "tile18": null, "tile19": null, "tile20": null, "tile21": null, "tile22": null, "tile23": null, "tile24": null, "tile25": null, "tile26": null, "tile27": null, "house": { "id": -1, "hand": ["tile14", "tile15", "tile16", "tile17", "tile18", "tile19", "tile20", "tile21", "tile22", "tile23", "tile24", "tile25", "tile26", "tile27"] }, "board": {}, "players": [{ "id": 0, "hand": ["tile0", "tile1", "tile2", "tile3", "tile4", "tile5", "tile6"] }, { "id": 1, "hand": ["tile7", "tile8", "tile9", "tile10", "tile11", "tile12", "tile13"] }] });
        var expectedMove = [{ "setTurn": { "turnIndex": 1 } }, { "set": { "key": "board", "value": { "root": { "leftNumber": 2, "rightNumber": 6 }, "leftMost": { "leftNumber": 2, "rightNumber": 6 }, "rightMost": { "leftNumber": 2, "rightNumber": 6 } } } }, { "set": { "key": "delta", "value": { "tileKey": "tile0", play: 1 } } }, { "setVisibility": { "key": "tile0", "visibleToPlayerIndexes": [0, 1] } }, { "set": { "key": "players", "value": [{ "id": 0, "hand": ["tile1", "tile2", "tile3", "tile4", "tile5", "tile6"] }, { "id": 1, "hand": ["tile7", "tile8", "tile9", "tile10", "tile11", "tile12", "tile13"] }] } }];
        expect(angular.equals(move, expectedMove)).toBe(true);
    });
    it("Player 1 finds an immediate move", function () {
        var move = aiService.createComputerMove(1, { "tile0": { "leftNumber": 2, "rightNumber": 6 }, "tile1": null, "tile2": null, "tile3": null, "tile4": null, "tile5": null, "tile6": null, "tile7": { "leftNumber": 1, "rightNumber": 3 }, "tile8": { "leftNumber": 5, "rightNumber": 5 }, "tile9": { "leftNumber": 1, "rightNumber": 4 }, "tile10": { "leftNumber": 4, "rightNumber": 6 }, "tile11": { "leftNumber": 2, "rightNumber": 3 }, "tile12": { "leftNumber": 4, "rightNumber": 4 }, "tile13": { "leftNumber": 1, "rightNumber": 6 }, "tile14": null, "tile15": null, "tile16": null, "tile17": null, "tile18": null, "tile19": null, "tile20": null, "tile21": null, "tile22": null, "tile23": null, "tile24": null, "tile25": null, "tile26": null, "tile27": null, "house": { "id": -1, "hand": ["tile14", "tile15", "tile16", "tile17", "tile18", "tile19", "tile20", "tile21", "tile22", "tile23", "tile24", "tile25", "tile26", "tile27"] }, "board": { "root": { "leftNumber": 2, "rightNumber": 6 }, "leftMost": { "leftNumber": 2, "rightNumber": 6 }, "rightMost": { "leftNumber": 2, "rightNumber": 6 } }, "players": [{ "id": 0, "hand": ["tile1", "tile2", "tile3", "tile4", "tile5", "tile6"] }, { "id": 1, "hand": ["tile7", "tile8", "tile9", "tile10", "tile11", "tile12", "tile13"] }], "delta": { "tileKey": "tile9", "play": Play.LEFT } });
        var expectedMove = [{ "setTurn": { "turnIndex": 0 } }, { "set": { "key": "board", "value": { "root": { "leftNumber": 2, "rightNumber": 6, "rightTile": { "leftNumber": 6, "rightNumber": 4 } }, "leftMost": { "leftNumber": 2, "rightNumber": 6 }, "rightMost": { "leftNumber": 6, "rightNumber": 4 } } } }, { "set": { "key": "delta", "value": { "tileKey": "tile10", "play": 1 } } }, { "setVisibility": { "key": "tile10", "visibleToPlayerIndexes": [0, 1] } }, { "set": { "key": "players", "value": [{ "id": 0, "hand": ["tile1", "tile2", "tile3", "tile4", "tile5", "tile6"] }, { "id": 1, "hand": ["tile7", "tile8", "tile9", "tile11", "tile12", "tile13"] }] } }];
        expect(angular.equals(move, expectedMove)).toBe(true);
    });
    it("Player 0 finds an immediate winning move", function () {
        var move = aiService.createComputerMove(0, { "tile0": { "leftNumber": 2, "rightNumber": 6 }, "tile1": { "leftNumber": 4, "rightNumber": 5 }, "tile2": { "leftNumber": 4, "rightNumber": 5 }, "tile3": { "leftNumber": 1, "rightNumber": 2 }, "tile4": null, "tile5": { "leftNumber": 1, "rightNumber": 1 }, "tile6": { "leftNumber": 3, "rightNumber": 3 }, "tile7": { "leftNumber": 1, "rightNumber": 3 }, "tile8": { "leftNumber": 5, "rightNumber": 5 }, "tile9": { "leftNumber": 1, "rightNumber": 4 }, "tile10": { "leftNumber": 4, "rightNumber": 6 }, "tile11": { "leftNumber": 2, "rightNumber": 3 }, "tile12": { "leftNumber": 4, "rightNumber": 4 }, "tile13": null, "tile14": { "leftNumber": 2, "rightNumber": 5 }, "tile15": null, "tile16": null, "tile17": null, "tile18": null, "tile19": null, "tile20": null, "tile21": null, "tile22": null, "tile23": null, "tile24": null, "tile25": null, "tile26": null, "tile27": null, "house": { "id": -1, "hand": ["tile14", "tile15", "tile16", "tile17", "tile18", "tile19", "tile20", "tile21", "tile22", "tile23", "tile24", "tile25", "tile26", "tile27"] }, "board": { "root": { "leftNumber": 2, "rightNumber": 6, "rightTile": { "leftNumber": 5, "rightNumber": 5, "rightTile": { "leftNumber": 4, "rightNumber": 4 } }, "leftTile": { "leftNumber": 1, "rightNumber": 2, "leftTile": { "leftNumber": 1, "rightNumber": 1 } } }, "leftMost": { "leftNumber": 1, "rightNumber": 1 }, "rightMost": { "leftNumber": 4, "rightNumber": 4 } }, "players": [{ "id": 0, "hand": ["tile1"] }, { "id": 1, "hand": ["tile4", "tile13"] }], "delta": { "tileKey": "tile10", "play": Play.RIGHT } });
        var expectedMove = [{ "endMatch": { "endMatchScores": [1, 0] } }, { "set": { "key": "board", "value": { "root": { "leftNumber": 2, "rightNumber": 6, "rightTile": { "leftNumber": 5, "rightNumber": 5, "rightTile": { "leftNumber": 4, "rightNumber": 4, "rightTile": { "leftNumber": 4, "rightNumber": 5 } } }, "leftTile": { "leftNumber": 1, "rightNumber": 2, "leftTile": { "leftNumber": 1, "rightNumber": 1 } } }, "leftMost": { "leftNumber": 1, "rightNumber": 1 }, "rightMost": { "leftNumber": 4, "rightNumber": 5 } } } }, { "set": { "key": "delta", "value": { "tileKey": "tile1", "play": 1 } } }, { "setVisibility": { "key": "tile1", "visibleToPlayerIndexes": [0, 1] } }];
        expect(angular.equals(move, expectedMove)).toBe(true);
    });
});
