describe("aiService", function () {
    /*it("Player 1 finds an immediate left Move", function() {
      let move = aiService.createComputerMove(
          1, {"tile0":null,"tile1":{"leftNumber":6,"rightNumber":6},"tile2":null,"tile3":null,"tile4":null,"tile5":null,"tile6":null,"tile7":{"leftNumber":1,"rightNumber":5},"tile8":{"leftNumber":1,"rightNumber":6},"tile9":{"leftNumber":3,"rightNumber":3},"tile10":{"leftNumber":3,"rightNumber":4},"tile11":{"leftNumber":0,"rightNumber":3},"tile12":{"leftNumber":2,"rightNumber":2},"tile13":{"leftNumber":0,"rightNumber":2},"tile14":null,"tile15":null,"tile16":null,"tile17":null,"tile18":null,"tile19":null,"tile20":null,"tile21":null,"tile22":null,"tile23":null,"tile24":null,"tile25":null,"tile26":null,"tile27":null,"house":{"id":-1,"hand":["tile14","tile15","tile16","tile17","tile18","tile19","tile20","tile21","tile22","tile23","tile24","tile25","tile26","tile27"]},"board":{"root":{"tileKey":"tile1"},"leftMost":"tile1","rightMost":"tile1"},"players":[{"id":0,"hand":["tile0","tile2","tile3","tile4","tile5","tile6"]},{"id":1,"hand":["tile7","tile8","tile9","tile10","tile11","tile12","tile13"]}],"delta":{"play":1,"tileKey":"tile1"}}, 6, 6);
      let expectedMove =
          [{"setTurn":{"turnIndex":0}},{"set":{"key":"board","value":{"root":{"tileKey":"tile1","leftTile":{"tileKey":"tile8"}},"leftMost":"tile8","rightMost":"tile1"}}},{"set":{"key":"delta","value":{"tileKey":"tile8","play":0}}},{"setVisibility":{"key":"tile8","visibleToPlayerIndexes":[0,1]}},{"set":{"key":"players","value":[{"id":0,"hand":["tile0","tile2","tile3","tile4","tile5","tile6"]},{"id":1,"hand":["tile7","tile9","tile10","tile11","tile12","tile13"]}]}}];
    expect(angular.equals(move, expectedMove)).toBe(true);
  });
  
    it("Player 1 finds an immediate right move", function() {
      let move = aiService.createComputerMove(
          1, {"tile0":null,"tile1":{"leftNumber":6,"rightNumber":6},"tile2":null,"tile3":{"leftNumber":2,"rightNumber":6},"tile4":null,"tile5":{"leftNumber":2,"rightNumber":4},"tile6":null,"tile7":{"leftNumber":1,"rightNumber":5},"tile8":{"leftNumber":1,"rightNumber":6},"tile9":{"leftNumber":3,"rightNumber":3},"tile10":{"leftNumber":3,"rightNumber":4},"tile11":{"leftNumber":0,"rightNumber":3},"tile12":{"leftNumber":2,"rightNumber":2},"tile13":{"leftNumber":0,"rightNumber":2},"tile14":null,"tile15":null,"tile16":null,"tile17":null,"tile18":null,"tile19":null,"tile20":null,"tile21":null,"tile22":null,"tile23":null,"tile24":null,"tile25":null,"tile26":null,"tile27":null,"house":{"id":-1,"hand":["tile14","tile15","tile16","tile17","tile18","tile19","tile20","tile21","tile22","tile23","tile24","tile25","tile26","tile27"]},"board":{"root":{"tileKey":"tile1","leftTile":{"tileKey":"tile8","leftTile":{"tileKey":"tile7"}},"rightTile":{"tileKey":"tile3","rightTile":{"tileKey":"tile5"}}},"leftMost":"tile7","rightMost":"tile5"},"players":[{"id":0,"hand":["tile0","tile2","tile4","tile6"]},{"id":1,"hand":["tile9","tile10","tile11","tile12","tile13"]}],"delta":{"play":1,"tileKey":"tile5"}}, 5, 4);
  
      let expectedMove =
          [{"setTurn":{"turnIndex":0}},{"set":{"key":"board","value":{"root":{"tileKey":"tile1","leftTile":{"tileKey":"tile8","leftTile":{"tileKey":"tile7"}},"rightTile":{"tileKey":"tile3","rightTile":{"tileKey":"tile5","rightTile":{"tileKey":"tile10"}}}},"leftMost":"tile7","rightMost":"tile10"}}},{"set":{"key":"delta","value":{"tileKey":"tile10","play":1}}},{"setVisibility":{"key":"tile10","visibleToPlayerIndexes":[0,1]}},{"set":{"key":"players","value":[{"id":0,"hand":["tile0","tile2","tile4","tile6"]},{"id":1,"hand":["tile9","tile11","tile12","tile13"]}]}}];
    expect(angular.equals(move, expectedMove)).toBe(true);
  });*/
    it("Player 1 finds an immediate first move", function () {
        var move = aiService.createComputerMove(1, { "tile0": null, "tile1": null, "tile2": null, "tile3": null, "tile4": null, "tile5": null, "tile6": null, "tile7": { "leftNumber": 0, "rightNumber": 6 }, "tile8": { "leftNumber": 6, "rightNumber": 6 }, "tile9": { "leftNumber": 2, "rightNumber": 3 }, "tile10": { "leftNumber": 3, "rightNumber": 5 }, "tile11": { "leftNumber": 2, "rightNumber": 6 }, "tile12": { "leftNumber": 3, "rightNumber": 6 }, "tile13": { "leftNumber": 2, "rightNumber": 4 }, "tile14": null, "tile15": null, "tile16": null, "tile17": null, "tile18": null, "tile19": null, "tile20": null, "tile21": null, "tile22": null, "tile23": null, "tile24": null, "tile25": null, "tile26": null, "tile27": null, "house": { "id": -1, "hand": ["tile14", "tile15", "tile16", "tile17", "tile18", "tile19", "tile20", "tile21", "tile22", "tile23", "tile24", "tile25", "tile26", "tile27"] }, "board": {}, "players": [{ "id": 0, "hand": ["tile0", "tile1", "tile2", "tile3", "tile4", "tile5", "tile6"] }, { "id": 1, "hand": ["tile7", "tile8", "tile9", "tile10", "tile11", "tile12", "tile13"] }], "delta": { "play": 3 } }, undefined, undefined);
        console.log("MOVE: " + JSON.stringify(move));
        var expectedMove = [{ "setTurn": { "turnIndex": 0 } }, { "set": { "key": "board", "value": { "root": { "tileKey": "tile8" }, "leftMost": "tile8", "rightMost": "tile8" } } }, { "set": { "key": "delta", "value": { "tileKey": "tile8", "play": 1 } } }, { "setVisibility": { "key": "tile8", "visibleToPlayerIndexes": [0, 1] } }, { "set": { "key": "players", "value": [{ "id": 0, "hand": ["tile0", "tile1", "tile2", "tile3", "tile4", "tile5", "tile6"] }, { "id": 1, "hand": ["tile7", "tile9", "tile10", "tile11", "tile12", "tile13"] }] } }];
        expect(angular.equals(move, expectedMove)).toBe(true);
    });
    /*it("Player 0 finds an immediate winning move", function() {
      let move = aiService.createComputerMove(
          0, {"tile0":{"leftNumber":2,"rightNumber":6},"tile1":{"leftNumber":4,"rightNumber":5},"tile2":{"leftNumber":4,"rightNumber":5},"tile3":{"leftNumber":1,"rightNumber":2},"tile4":null,"tile5":{"leftNumber":1,"rightNumber":1},"tile6":{"leftNumber":3,"rightNumber":3},"tile7":{"leftNumber":1,"rightNumber":3},"tile8":{"leftNumber":5,"rightNumber":5},"tile9":{"leftNumber":1,"rightNumber":4},"tile10":{"leftNumber":4,"rightNumber":6},"tile11":{"leftNumber":2,"rightNumber":3},"tile12":{"leftNumber":4,"rightNumber":4},"tile13":null,"tile14":{"leftNumber":2,"rightNumber":5},"tile15":null,"tile16":null,"tile17":null,"tile18":null,"tile19":null,"tile20":null,"tile21":null,"tile22":null,"tile23":null,"tile24":null,"tile25":null,"tile26":null,"tile27":null,"house":{"id":-1,"hand":["tile14","tile15","tile16","tile17","tile18","tile19","tile20","tile21","tile22","tile23","tile24","tile25","tile26","tile27"]},"board":{"root":{"leftNumber":2,"rightNumber":6,"rightTile":{"leftNumber":5,"rightNumber":5,"rightTile":{"leftNumber":4,"rightNumber":4}},"leftTile":{"leftNumber":1,"rightNumber":2,"leftTile":{"leftNumber":1,"rightNumber":1}}},"leftMost":{"leftNumber":1,"rightNumber":1},"rightMost":{"leftNumber":4,"rightNumber":4}},"players":[{"id":0,"hand":["tile1"]},{"id":1,"hand":["tile4","tile13"]}],"delta":{"tileKey":"tile10","play":Play.RIGHT}});
      let expectedMove = [{"setVisibility":{"key":"tile0","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile1","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile2","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile3","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile4","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile5","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile6","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile7","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile8","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile9","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile10","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile11","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile12","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile13","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile14","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile15","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile16","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile17","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile18","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile19","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile20","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile21","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile22","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile23","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile24","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile25","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile26","visibleToPlayerIndexes":[0,1]}},{"setVisibility":{"key":"tile27","visibleToPlayerIndexes":[0,1]}},{"setTurn":{"turnIndex":0}}];
      expect(angular.equals(move, expectedMove)).toBe(true);
    });
  
    it("Player 0 finds a buy play", function() {
      let move = aiService.createComputerMove(
          0, {"tile0":{"leftNumber":2,"rightNumber":6},"tile1":{"leftNumber":0,"rightNumber":5},"tile2":{"leftNumber":4,"rightNumber":5},"tile3":{"leftNumber":1,"rightNumber":2},"tile4":{"leftNumber":6,"rightNumber":6},"tile5":{"leftNumber":1,"rightNumber":1},"tile6":{"leftNumber":3,"rightNumber":3},"tile7":{"leftNumber":1,"rightNumber":3},"tile8":null,"tile9":{"leftNumber":1,"rightNumber":4},"tile10":{"leftNumber":4,"rightNumber":6},"tile11":{"leftNumber":2,"rightNumber":3},"tile12":null,"tile13":null,"tile14":null,"tile15":null,"tile16":null,"tile17":null,"tile18":null,"tile19":null,"tile20":null,"tile21":null,"tile22":null,"tile23":null,"tile24":null,"tile25":null,"tile26":null,"tile27":null,"house":{"id":-1,"hand":["tile14","tile15","tile16","tile17","tile18","tile19","tile20","tile21","tile22","tile23","tile24","tile25","tile26","tile27"]},"board":{"root":{"leftNumber":2,"rightNumber":6,"rightTile":{"leftNumber":6,"rightNumber":4,"rightTile":{"leftNumber":4,"rightNumber":1,"rightTile":{"leftNumber":1,"rightNumber":3,"rightTile":{"leftNumber":3,"rightNumber":2}}}},"leftTile":{"leftNumber":1,"rightNumber":2,"leftTile":{"leftNumber":1,"rightNumber":1}}},"leftMost":{"leftNumber":1,"rightNumber":1},"rightMost":{"leftNumber":3,"rightNumber":2}},"players":[{"id":0,"hand":["tile1","tile2","tile4"]},{"id":1,"hand":["tile8","tile12","tile13"]}],"delta":{"tileKey":"tile14","play":Play.BUY}});
      let expectedMove = [{"setTurn":{"turnIndex":0}},{"set":{"key":"board","value":{"root":{"leftNumber":2,"rightNumber":6,"rightTile":{"leftNumber":6,"rightNumber":4,"rightTile":{"leftNumber":4,"rightNumber":1,"rightTile":{"leftNumber":1,"rightNumber":3,"rightTile":{"leftNumber":3,"rightNumber":2}}}},"leftTile":{"leftNumber":1,"rightNumber":2,"leftTile":{"leftNumber":1,"rightNumber":1}}},"leftMost":{"leftNumber":1,"rightNumber":1},"rightMost":{"leftNumber":3,"rightNumber":2}}}},{"set":{"key":"delta","value":{"tileKey":"tile14","play":2}}},{"setVisibility":{"key":"tile14","visibleToPlayerIndexes":[0]}},{"set":{"key":"players","value":[{"id":0,"hand":["tile1","tile2","tile4","tile14"]},{"id":1,"hand":["tile8","tile12","tile13"]}]}}];
      expect(angular.equals(move, expectedMove)).toBe(true);
    });
  
    it("Player 0 finds a pass play", function() {
      let move = aiService.createComputerMove(
          0, {"tile0":{"leftNumber":2,"rightNumber":6},"tile1":{"leftNumber":0,"rightNumber":5},"tile2":{"leftNumber":4,"rightNumber":5},"tile3":{"leftNumber":1,"rightNumber":2},"tile4":{"leftNumber":6,"rightNumber":6},"tile5":{"leftNumber":1,"rightNumber":1},"tile6":{"leftNumber":3,"rightNumber":3},"tile7":{"leftNumber":1,"rightNumber":3},"tile8":null,"tile9":{"leftNumber":1,"rightNumber":4},"tile10":{"leftNumber":4,"rightNumber":6},"tile11":{"leftNumber":2,"rightNumber":3},"tile12":null,"tile13":null,"tile14":null,"tile15":null,"tile16":null,"tile17":null,"tile18":null,"tile19":null,"tile20":null,"tile21":null,"tile22":null,"tile23":null,"tile24":null,"tile25":null,"tile26":null,"tile27":null,"board":{"root":{"leftNumber":2,"rightNumber":6,"rightTile":{"leftNumber":6,"rightNumber":4,"rightTile":{"leftNumber":4,"rightNumber":1,"rightTile":{"leftNumber":1,"rightNumber":3,"rightTile":{"leftNumber":3,"rightNumber":2}}}},"leftTile":{"leftNumber":1,"rightNumber":2,"leftTile":{"leftNumber":1,"rightNumber":1}}},"leftMost":{"leftNumber":1,"rightNumber":1},"rightMost":{"leftNumber":3,"rightNumber":2}},"players":[{"id":0,"hand":["tile1","tile2","tile4"]},{"id":1,"hand":["tile8","tile12","tile13"]}],"delta":{"tileKey":"tile14","play":Play.BUY}});
      let expectedMove = [{"setTurn":{"turnIndex":1}}];
      expect(angular.equals(move, expectedMove)).toBe(true);
    });*/
});
